apiVersion: v1
kind: Service
metadata:
  name: pmysql-lb-1
  namespace: default
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  type: LoadBalancer
  selector:
    name: db-cluster
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
