apiVersion: v1
kind: Service
metadata:
  name: lineblocs-com
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: lineblocs-com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lineblocs-com

spec:
  replicas: 1
  selector:
    matchLabels:
      app: lineblocs-com
      firewall: open

  template:
    metadata:
      labels:
        app: lineblocs-com
    spec:
      containers:
      - name: app
        image: 754569496111.dkr.ecr.ca-central-1.amazonaws.com/lineblocs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9000
            httpHeaders:
            - name: X-Health
              value: health
          initialDelaySeconds: 3
          periodSeconds: 3
      imagePullSecrets:
      - name: lineblocs-regcred
