apiVersion: v1
kind: Service
metadata:
  name: lineblocs-com
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: lineblocs-com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lineblocs-com

spec:
  replicas: 1
  selector:
    matchLabels:
      app: lineblocs-com

  template:
    metadata:
      labels:
        app: lineblocs-com
    spec:
      containers:
      - name: app
        image: lineblocs/site:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: X-Health
              value: health
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            cpu: "64m"
            memory: "32Mi"
          limits:
            cpu: "4096m"
            memory: "16384Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: com-hpa
 namespace: default
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
      selectPolicy: Max
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment 
    name: lineblocs-com