apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opensips
  namespace: voip
  labels:
    component: opensips
spec:
  selector:
    matchLabels:
      component: opensips
  template:
    metadata:
      name: opensips
      labels:
        component: opensips
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: rtpproxy
          image: 754569496111.dkr.ecr.ca-central-1.amazonaws.com/rtpproxy:latest
        - name: opensips
          image: 754569496111.dkr.ecr.ca-central-1.amazonaws.com/opensips:latest
          resources:
            requests:
              cpu: "100m"
              memory: "1024Mi"
            limits:
              cpu: "300m"
              memory: "2048Mi"
          env:
            - name: DB_HOST
              value: 104.248.107.119
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: "4ChTXGuEUtrj6b4H"
            - name: DB_NAME
              value: opensips
            - name: RTPPROXY_IPV4
              value: 127.0.0.1
            - name: LINEBLOCS_KEY
              value: xxx
      imagePullSecrets:
        - name: voip-regcred
      nodeSelector:
        routerNode: 'true'
